# FROM node:20
# WORKDIR /App
# COPY package*.json ./
# RUN npm install
# COPY . .
# EXPOSE 5173
# CMD ["npm","run","dev"]
# # 422 => 128

# FROM node:20-alpine
# WORKDIR /App
# COPY package*.json ./
# RUN npm install
# COPY . .
# EXPOSE 5173
# CMD ["npm","run","dev"]
# # 422 => 128

FROM node:20-alpine AS builder
WORKDIR /app
COPY ./package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine as production
COPY --from=builder /app/dist ./usr/share/nginx/html

EXPOSE 80
CMD ["nginx","-g","daemon off"]
# 93 => 26